//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Article
    {
        public int aid { get; set; }
        public Nullable<int> cid { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<System.DateTime> ptime { get; set; }
        public Nullable<bool> istop { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> hits { get; set; }
        public Nullable<int> comments { get; set; }
        public string ahtml { get; set; }
    }
}
