//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_User
    {
        
        public int uid { get; set; }

        //[Required(ErrorMessage = "用户名不能为空")]
        public string uname { get; set; }

        //[DataType(DataType.Password)]
        //[Required(ErrorMessage = "密码不能为空")]
        public string upwd { get; set; }

        //[DataType(DataType.Password)]
        //[Compare("upwd",ErrorMessage ="密码必须一致")]
       
        public string nname { get; set; }

        //[Required(ErrorMessage = "电话号码不能为空")]
        
        public string mobile { get; set; }
        public string face { get; set; }
        public Nullable<bool> admin { get; set; }
    }
}
