//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSEntities : DbContext
    {
        public CMSEntities()
            : base("name=CMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CMS_Article> CMS_Article { get; set; }
        public virtual DbSet<CMS_Category> CMS_Category { get; set; }
        public virtual DbSet<CMS_Comment> CMS_Comment { get; set; }
        public virtual DbSet<CMS_Keyword> CMS_Keyword { get; set; }
        public virtual DbSet<CMS_User> CMS_User { get; set; }
        public virtual DbSet<V_CMS_Article> V_CMS_Article { get; set; }
        public virtual DbSet<V_CMS_Comment> V_CMS_Comment { get; set; }
    }
}
