//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CMS_Comment
    {
        public int cmid { get; set; }
        public Nullable<int> aid { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<System.DateTime> cmtime { get; set; }
        public string cmhtml { get; set; }
        public string nname { get; set; }
        public string face { get; set; }
    }
}
